### ISSUE TITLE
Debug Issue #1 using hashes

### ISSUE THREAD

**Issue by jenjohnson7** [End-to-end-provenance/python_tools#6]
<img width="579" alt="debug hash when added w o with open" src="https://user-images.githubusercontent.com/15007454/28227283-3ded07b6-68a7-11e7-847b-cc57768935e4.png">

Hashes not being detected when manually adding files instead of automatically using db file_accesses
Find hashes a different way.

**Comment by jenjohnson7** [comment]
For script_nums >1:
already-existing files are not being detected because of differences in numbering the process nodes.
Find a per-script way to keep the file dictionaries?

<img width="769" alt="multiple input scripts" src="https://user-images.githubusercontent.com/15007454/28273425-6264ba1c-6adc-11e7-8a19-3130ba93a35e.png">

**Comment by jenjohnson7** [comment]
Hashes now checked even if added in the special case when file not opened with syntax: with open() as f. 
Debugged the outfiles dictionary to add extra layer to nested dictionary so that files are not overwritten.

**Comment by MKLau** [comment]
Nice work, Jen!
